//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularPlaybookDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticker
    {
        public Ticker()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int TickerId { get; set; }
        public string Symbol { get; set; }
        public string StockName { get; set; }
        public decimal StockLastPrice { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
